### ISSUE TITLE
Segfault on ARM

### ISSUE THREAD

**Issue by Baggypants** [marcan/rtlmic#5]
Trying to get it to run on ARM and it segfaults. I compiled it with -g and heres a gdb output, hope it's helpful. it runs fine on x86_64

```bash
Starting program: /root/rtlmic/rtlmic -e 1 -M 50 97700000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x76a4d440 (LWP 19010)]
[New Thread 0x769cc440 (LWP 19012)]

Thread 1 "rtlmic" received signal SIGSEGV, Segmentation fault.
0x000111b8 in generate_lpf (taps=0x0, ntaps=21, fs=300000, width=100000) at rtlmic.c:139
139	    taps[M] = fwT0;
(gdb) backtrace
#0  0x000111b8 in generate_lpf (taps=0x0, ntaps=21, fs=300000, width=100000) at rtlmic.c:139
#1  0x000116f4 in init_channel (c=0) at rtlmic.c:194
#2  0x00013c18 in main (argc=6, argv=0x7effedd4) at rtlmic.c:700

```

**Comment by mark-mdgam** [comment]
Any new insight on this?
